### ISSUE TITLE
Missing link in docs for the `template` parameter 

### ISSUE THREAD

**Issue by aucampia** [hashicorp/packer-plugin-vagrant#92] opened 2023-06-13 14:45 UTC
It seems like "here" on like 48 below should be a hyperlink, but it is not:

https://github.com/hashicorp/packer-plugin-vagrant/blob/f21234ffae9cc7ead0d385b9af8443304ede341d/docs-partials/builder/vagrant/Config-not-required.mdx?plain=1#L47-L50

I would help fix it, but it is not clear what it should point to. 

It should possibly be this: https://github.com/hashicorp/packer-plugin-vagrant/blob/f21234ffae9cc7ead0d385b9af8443304ede341d/post-processor/vagrant/virtualbox.go#L178-L181

**Comment by aucampia** [comment] 2023-06-14 09:20
Actually after further investigation, I think the default template is:

https://github.com/hashicorp/packer-plugin-vagrant/blob/2f25ae2c1bbdadf6f3385fc9683e25e7edb966b3/builder/vagrant/step_create_vagrantfile.go#L28-L43

**Comment by VishnuJin** [comment] 2024-02-03 06:59
possible duplicate of #20

**Closed** 2024-02-05 15:22 UTC
